//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroUnidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LibroUnidades()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public int idLibroUnidades { get; set; }
        public Nullable<int> idLibro { get; set; }
        public Nullable<int> idUbicacion { get; set; }
        public Nullable<int> codigo { get; set; }
    
        public virtual Libro Libro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
    }
}
