//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int idVenta { get; set; }
        public Nullable<int> idLibroUnidades { get; set; }
        public string FechaVenta { get; set; }
        public string NombreCliente { get; set; }
        public Nullable<int> Precio { get; set; }
    
        public virtual LibroUnidades LibroUnidades { get; set; }
    }
}
